### ISSUE TITLE
How to add task to a tasklist?

### ISSUE THREAD

**Issue by khurshid-alam** [bartosz-maciaszek/php-rtm#2]
I have uploaded folders & files on my server & successfully authorized it. Now when ever I try to add a task it shows an error : `Fatal error: Uncaught exception 'Rtm\Exception' with message 'Invalid signature'`

Here is the code:

```
require_once 'bootstrap.php';
use Rtm\Rtm;

$rtm = new Rtm;
$rtm->setApiKey(API_KEY);
$rtm->setSecret(SECRET);
$token = file_get_contents("oauth.token");
$rtm->setAuthToken("$token");
$task = $rtm->getService(Rtm::SERVICE_TASKS);
$res = $task->add('New Task', '1698765', 0, 0);
print_r($res);
```

And `print_r($res)` shows:

> Fatal error: Uncaught exception 'Rtm\Exception' with message 'Invalid signature' in        /home/user/public_html/rtm/src/Rtm/Client.php:125 Stack trace: #0 /home/user/public_html/rtm/src/Rtm/Client.php(81): Rtm\Client->createResponse('{"rsp":{"stat":...') #1 /home/user/public_html/rtm/src/Rtm/Rtm.php(358): Rtm\Client->call('rtm.tasks.add', Array) #2 /home/user/public_html/rtm/src/Rtm/Service/Tasks.php(59): Rtm\Rtm->call('rtm.tasks.add', Array) #3 /home/user/public_html/rtm/sample-app/land-bill.php(21): Rtm\Service\Tasks->add('New-Php', '16594225', 0, 0) #4 {main} Next exception 'Rtm\Exception' with message 'rtm.tasks.add: Invalid signature' in /home/user/public_html/rtm/src/Rtm/Client.php:85 Stack trace: #0 /home/user/public_html/rtm/src/Rtm/Rtm.php(358): Rtm\Client->call('rtm.tasks.add', Array) #1 /home/user/public_html/rtm/src/Rtm/Service/Tasks.php(59): Rtm\Rtm->call('rtm.tasks.add', Array) #2 /home/user/public_html/rtm/sample-app/land- in /home/user/public_html/rtm/src/Rtm/Client.php on line 85 

What am I doing wrong?

**Comment by bartosz-maciaszek** [comment]
Hmm, it looks like auth token you provide is invalid. What do you have in "oauth.token" file?

**Comment by khurshid-alam** [comment]
I saved  `$_SESSION['RTM_AUTH_TOKEN']` into oauth.token (for now). Getting 'taskslist & all tasks within a tasklist' is working fine.Problem occurs whenever it needs 'write' access (& I have 'delete' access).  I also tried with checkToken(), which seems working ok.

```
$auth_info = $rtm->getService(Rtm::SERVICE_AUTH)->checkToken();
print_r($auth_info);
```

Output:

> Rtm\DataContainer Object ( [attributes:Rtm\DataContainer:private] => Array ( [token] => f9a545dfbf65756775g7der67*..........[perms] => delete [user] => Rtm\DataContainer Object ( [attributes:Rtm\DataContainer:private] => Array ( [id] => 2867552 [username] => myusername [fullname] => my full name ) ) ) )

**Comment by bartosz-maciaszek** [comment]
Hi Khurshid.
I was able to reproduce the bug. I'm going to investigate where is the problem.

**Comment by bartosz-maciaszek** [comment]
So the problem is you have not provided timeline for a request, while it is required in that method.

https://www.rememberthemilk.com/services/api/methods/rtm.tasks.add.rtm

Try:

```
$timeline = $rtm->getService(Rtm::SERVICE_TIMELINES)->create();
```

and then:

```
$task = $rtm->getService(Rtm::SERVICE_TASKS);
$res = $task->add('New Task', '1698765', null, $timeline);
```

**Comment by bartosz-maciaszek** [comment]
In version 1.0.4 you can set timeline per service instead of setting it for every single method.

Therefore, you can do it like this:

```
$timeline = $rtm->getService(Rtm::SERVICE_TIMELINES)->create();

$tasks = $rtm->getService(Rtm::SERVICE_TASKS);
$tasks->setTimeline($timeline);

$tasks->add('New task #1');
$tasks->add('New task #2');
$tasks->add('New task #3', 1698765);
```

**Comment by khurshid-alam** [comment]
Thanks. That worked.
